services:
  bot:
    build:
      context: .
      target: bot
    container_name: p2c-bot
    restart: unless-stopped
    env_file: .env
    environment:
      DB_PATH: /app/data/bot_users.db
    volumes:
      - ./data:/app/data

  admin:
    build:
      context: .
      target: admin
    container_name: p2c-admin
    restart: unless-stopped
    env_file: .env
    environment:
      DB_PATH: /app/data/bot_users.db
    volumes:
      - ./data:/app/data
    ports:
      - "8088:8088"
